package com.jihoon.java.exception;

public class ExceptionMain {

	public static void main(String[] args) {
		
		try{
			int array[] = new int [6];
		
			array[0] = 5;
			array[5] = 10;
			array[6] = 11;

		}catch(ArrayIndexOutOfBoundsException e){  // e: nameOfException
/*			String msg = e.toString();
			System.out.println(msg);*/
		}
		finally{
			System.out.println();
		}
		
		System.out.println("다섯버번째 값 : array[5]");
	}
}
