package com.jihoon.java.exception;

public class ExceptionMain {

	public static void main(String[] args) {
		
		try{
			int array[] = new int [6];
		
			array[5] = 10;
			array[6] = 11;

		}catch(ArrayIndexOutOfBoundsException e){  // e: nameOfException
			String msg = e.toString();
			System.out.println(msg);
		}
		
		System.out.println("시스템이 완료되었습니다");
	}
}
